### ISSUE TITLE
Why scope do NOT be asked in access_confirm page?

### ISSUE THREAD

**Issue by BigGitWorld** [LookBackInTheRain/oauth-boot#13]
Hi.
Why scope do not be asked in the access confirmation page from user, while client application authorization request URL have scope=select?
 http://ip:port/oauth/authorize?response_type=code&client_id=client&client_secret=123qwe&redirect_uri=http://localhost:9000&scope=select

**Comment by LookBackInTheRain** [comment]
因为现在用不到scope的功能，所以没有处理，将其隐藏了
