### ISSUE TITLE
Error processing condition on club.yuit.oauth.boot.config.auth2.TokenStoreConfig.jwtAccessTokenConverter

### ISSUE THREAD

**Issue by dreamPis** [LookBackInTheRain/oauth-boot#2]
Error processing condition on club.yuit.oauth.boot.config.auth2.TokenStoreConfig.jwtAccessTokenConverter

启动tokenStoreConfig报错

**Comment by LookBackInTheRain** [comment]
把完整的错误信息贴上来，没法看啊

**Comment by dreamPis** [comment]
springboot用2.0.6   就会在ConditionalOnMissingBean 注解的地方报错
改成2.0.5就好了

**Comment by LookBackInTheRain** [comment]
升级太快，，快跟不上了，后面再更新吧

**Comment by dreamPis** [comment]
我之前的一个改成2.0.6的 启动不出问题

**Comment by LookBackInTheRain** [comment]
OK，之后会升级下Spring Boot 版本试试
