### ISSUE TITLE
授权页面表单代码问题

### ISSUE THREAD

**Issue by LeeAli** [LookBackInTheRain/oauth-boot#4]
你的代码是有问题的,如果以你这种方式的话默认,授权范围默认是false,直接导致授权失败,正确代码应该如下
`<form method="post" th:action="@{/oauth/authorize}">
                <input type="hidden" name="user_oauth_approval" value="true">
                <input type="hidden" name="_csrf" th:value="${_csrf.getToken()}"/>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" checked="checked" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">昵称,身份和头像</label>
                </div>
                <div th:each="item:${scopes}">
                    <input type="radio" th:name="'scope.'+${item}" value="true" hidden="hidden" checked="checked">
                </div>
                <p class="card-text" style="color: #dc3545;font-size: 12px">授权后表表明您已同意Oauth2协议</p>
                <button type="submit" class="btn btn-outline-danger">同意授权</button>
            </form>`

**Comment by LookBackInTheRain** [comment]
感谢提醒，粗心了
