### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by CoderBoyBoy** [LookBackInTheRain/oauth-boot#8]
您好请教个问题，按照loginProcessUrl="/auth/authorize"配置后，点击登录提示404，我也没找了/auth/authorize端点定义，请问这是个什么机制？
祝好！

**Comment by LookBackInTheRain** [comment]
具体请看 [SecurityConfig.java](https://github.com/LookBackInTheRain/oauth-boot/blob/master/src/main/java/club/yuit/oauth/boot/config/SecurityConfig.java) security配置
